### ISSUE TITLE
E/FlutterLoader(11738): Flutter initialization failed.

### ISSUE THREAD

**Issue by AliReza-Pro-grammer** [AbdOoSaed/flutter_cached_pdfview#39]
ok, so once i try to run the app this happen...
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at
https://flutter.dev/go/android-project-migration
to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Launching lib\main.dart on G011A in debug mode...
 lib\main.dart
√ Built build\app\outputs\flutter-apk\app-debug.apk.
E/FlutterLoader(11738): Flutter initialization failed.
E/FlutterLoader(11738): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.int2.ecommerce_int2-1/base.apk"],nativeLibraryDirectories=[/data/app/com.int2.ecommerce_int2-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
E/FlutterLoader(11738): 	at java.util.concurrent.FutureTask.report(FutureTask.java:93)
E/FlutterLoader(11738): 	at java.util.concurrent.FutureTask.get(FutureTask.java:163)
E/FlutterLoader(11738): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:178)
E/FlutterLoader(11738): 	at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java:78)
E/FlutterLoader(11738): 	at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:145)
E/FlutterLoader(11738): 	at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:91)
E/FlutterLoader(11738): 	at com.int2.ecommerce_int2.MainActivity.onCreate(MainActivity.kt:10)
E/FlutterLoader(11738): 	at android.app.Activity.performCreate(Activity.java:5990)
E/FlutterLoader(11738): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/FlutterLoader(11738): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/FlutterLoader(11738): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/FlutterLoader(11738): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/FlutterLoader(11738): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/FlutterLoader(11738): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/FlutterLoader(11738): 	at android.os.Looper.loop(Looper.java:135)
E/FlutterLoader(11738): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/FlutterLoader(11738): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader(11738): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/FlutterLoader(11738): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/FlutterLoader(11738): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/FlutterLoader(11738): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.int2.ecommerce_int2-1/base.apk"],nativeLibraryDirectories=[/data/app/com.int2.ecommerce_int2-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
E/FlutterLoader(11738): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/FlutterLoader(11738): 	at java.lang.System.loadLibrary(System.java:988)
E/FlutterLoader(11738): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:129)
E/FlutterLoader(11738): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:123)
E/FlutterLoader(11738): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/FlutterLoader(11738): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/FlutterLoader(11738): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/FlutterLoader(11738): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(11738): FATAL EXCEPTION: main
E/AndroidRuntime(11738): Process: com.int2.ecommerce_int2, PID: 11738
E/AndroidRuntime(11738): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.int2.ecommerce_int2/com.int2.ecommerce_int2.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.int2.ecommerce_int2-1/base.apk"],nativeLibraryDirectories=[/data/app/com.int2.ecommerce_int2-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
E/AndroidRuntime(11738): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime(11738): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime(11738): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime(11738): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime(11738): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11738): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(11738): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(11738): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11738): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(11738): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(11738): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(11738): Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.int2.ecommerce_int2-1/base.apk"],nativeLibraryDirectories=[/data/app/com.int2.ecommerce_int2-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
E/AndroidRuntime(11738): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:243)
E/AndroidRuntime(11738): 	at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java:78)
E/AndroidRuntime(11738): 	at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:145)
E/AndroidRuntime(11738): 	at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:91)
E/AndroidRuntime(11738): 	at com.int2.ecommerce_int2.MainActivity.onCreate(MainActivity.kt:10)
E/AndroidRuntime(11738): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime(11738): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(11738): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime(11738): 	... 10 more
E/AndroidRuntime(11738): Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.int2.ecommerce_int2-1/base.apk"],nativeLibraryDirectories=[/data/app/com.int2.ecommerce_int2-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
E/AndroidRuntime(11738): 	at java.util.concurrent.FutureTask.report(FutureTask.java:93)
E/AndroidRuntime(11738): 	at java.util.concurrent.FutureTask.get(FutureTask.java:163)
E/AndroidRuntime(11738): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:178)
E/AndroidRuntime(11738): 	... 17 more
E/AndroidRuntime(11738): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.int2.ecommerce_int2-1/base.apk"],nativeLibraryDirectories=[/data/app/com.int2.ecommerce_int2-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
E/AndroidRuntime(11738): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime(11738): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime(11738): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:129)
E/AndroidRuntime(11738): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:123)
E/AndroidRuntime(11738): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(11738): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(11738): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(11738): 	at java.lang.Thread.run(Thread.java:818)
Exited (1)

the problem will be gone by disabling "flutter_cached_pdfview: ^0.3.3" in pubspec.yamel
thank you.

**Comment by yongjieYuan** [comment]
It's the same to me, it cannot build normally when I pub get this dependency.

The error like this:
A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable

**Comment by AbdOoSaed** [comment]
@yongjieYuan  @AliReza-Pro-grammer 
try this solutions
https://stackoverflow.com/questions/57606462/a-failure-occurred-while-executing-com-android-build-gradle-internal-tasks
