### ISSUE TITLE
Some Android phones fail to load heavier pdfs

### ISSUE THREAD

**Issue by sirajulhudalabs** [AbdOoSaed/flutter_cached_pdfview#50]
**Describe the bug**
Issue reported on Firebase crashlytics

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.barteksc.pdfviewer.PdfFile.getPageAtOffset(float, float)' on a null object reference
       at com.github.barteksc.pdfviewer.DragPinchManager.checkLinkTapped(DragPinchManager.java:88)
       at com.github.barteksc.pdfviewer.DragPinchManager.onSingleTapConfirmed(DragPinchManager.java:69)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by AbdOoSaed** [comment]
please provide a sample of heavy pdf
