### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

### ISSUE THREAD

**Issue by maxzod** [AbdOoSaed/flutter_cached_pdfview#54]
**Describe the bug**
cant load pdf from firebase storage (stuck on downloading)
`  flutter_cached_pdfview: ^0.4.0-nullsafety
`
**exception**
```
E/flutter (29464): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
E/flutter (29464): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (29464): <asynchronous suspension>
E/flutter (29464): #1      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:20)
E/flutter (29464): <asynchronous suspension>
E/flutter (29464): #2      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:153:20)
E/flutter (29464): <asynchronous suspension>
E/flutter (29464): #3      CacheObjectProvider._migrateOldDbPath (package:flutter_cache_manager/src/storage/cache_info_repositories/cache_object_provider.dart:208:29)
E/flutter (29464): <asynchronous suspension>
E/flutter (29464): #4      CacheObjectProvider._getPath (package:flutter_cache_manager/src/storage/cache_info_repositories/cache_object_provider.dart:202:5)
E/flutter (29464): <asynchronous suspension>
E/flutter (29464): #5      CacheObjectProvider.open (package:flutter_cache_manager/src/storage/cache_info_repositories/cache_object_provider.dart:28:16)
E/flutter (29464): <asynchronous suspension>
E/flutter (29464): #6      new CacheStore.<anonymous closure> (package:flutter_cache_manager/src/cache_store.dart)
E/flutter (29464): <asynchronous suspension>
E/flutter (29464):
```

- OS: Android
- Version : 11
- Flutter (Channel stable, 2.0.3)
- code 
 ```
        PDF(
          onError: (error) => Logger().e(error.toString()),
          onPageError: (page, error) => Logger().e('$page: ${error.toString()}'),
          onPageChanged: (int? page, int? total) => Logger().e('page change: $page/$total'),
        ).cachedFromUrl(
          'https://firebasestorage.googleapis.com/v0/b/three-6bc5c.appspot.com/o/New%20Microsoft%20Word%20Document.pdf?alt=media&token=7ce24408-c636-4fde-9f39-9e24d835fbf3',
        ),
```

**Comment by maxzod** [comment]
now it works 
idk which version  i am using but it now works after leave the version  empty and stop the app then rebuild it again

``  flutter_cached_pdfview :  ``

**Comment by AbdOoSaed** [comment]
fix for ur issue is just run `flutter clean`

u can check what package version u use in pubspec.lock

because it not good to leave the version empty 

this may cause some issues when I make some breaking changes in a new version
